name: Oscars-workflow

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v2

      - name: Python set up
        uses: action/setup-python@v2
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          
        
