version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes: 
      - metadata-volume:/app/uploads/metadata
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:

volumes:
  metadata-volume: