name: GitHub Actions - Terraform Plan

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials file
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/config

    - name: Terraform Init
      run: terraform init
      working-directory: ./iac

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./iac

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./iac

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./iac