# ...existing code...
    - name: Configure AWS credentials file
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/config

    - name: Terraform Init
      run: terraform init
      working-directory: ./iac

    - name: Terraform Format
      run: terraform fmt -check -diff
      working-directory: ./iac

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./iac

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./iac